services:
  # Frontend Service
  - type: web
    name: naga-sabot-frontend
    env: node
    buildCommand: |
      npm install
      npm run build
    startCommand: node dist/naga-sabot/server/server.mjs
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000

  # Backend Service
  - type: web
    name: naga-sabot-backend
    env: python
    buildCommand: |
      apt-get update && apt-get install -y build-essential python3-dev
      pip install -r flask-backend/requirements.txt
    startCommand: cd flask-backend && gunicorn --bind 0.0.0.0:$PORT --workers 1 --threads 8 --timeout 0 app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PORT
        value: 10001
      - key: CUDA_VISIBLE_DEVICES
        value: "-1" 